### PR TITLE
Syntax Highlighting, Compilation, a P Theme File, Problem Reporting

### PR DESCRIPTION
**Pull request by suesther**
Preliminary instructions to install this extension:
1. Clone this repository.
2. cd into this repository and call 'npm install'
3. Run 'cmd' 'shift' 'B' on this repository in VSCode to build this project.
4. Move this folder into the ~/.vscode/extensions directory.
5. Add {"identifier":{"id":"undefined_publisher.peasy-ide-vscode"},"version":"0.0.1","location":{"$mid":1,"path":"~/.vscode/extensions/peasy-ide-vscode","scheme":"file"},"relativeLocation":"peasy-ide-vscode"} to ~/.vscode/extensions/extensions.json
6. Restart VS Code.
7. Any P files should now be populated with syntax highlighting! Use P's Custom Theme by selecting with the dropdown at Code > Settings > Theme > Color Theme.

Further P Extension Support:
1. Compilation: Open any P project folder. Navigate to a file that ends with .p or .pproj and press 'f5' to compile. 
2. Use P's Custom Theme by selecting with the dropdown at Code > Settings > Theme > Color Theme.\
3. P should now support Errors that occur during compilation in the Problems panel. 

**Section 1: Summary** 
This extension so far supports syntax highlighting, a new custom P theme file, compilation when the user presses f5, and problem reporting within the VSCode IDE. The P theme and grammar file now groups together different keywords based on the Quip document as well as different types, constants, expressions, statements, and other keywords. 
I provided error support by implementing a task that runs in the background and re-compiles the program every time it detects a user change. A user can navigate to the Problems panel in order to view the errors their program encounters currently. 
I also provided compilation support by using configurations.keybindings to bind the command 'p.run' to the key f5.

ERROR REPORTING SUPPORT
error_reporting
SYNTAX HIGHLIGHTING + P CUSTOM THEME FILE 
syntax_highlighting
RUNNING F5 RESULT
Screenshot 2023-06-16 at 11 11 03 AM

Section 2: Testing
I tested my code by running an npm watch task in the background every time VSCode launched my extension that translated my typescript files into javascript files. Then, pressing f5 would launch the extension inside a folder inside VS Code and compile the javascript code. I could open a sample file in P where I could see the changes I made affect the file.

### CODE REVIEW

**Comment by aman-goel** [comment]
FYI, to use npm from https://www.npmjs.com/, I created a new https://www.npmjs.com/ account and do the following instead of `npm install`:
```
npm login --auth-type=legacy --registry=https://registry.npmjs.org
npm install --auth-type=legacy --registry=https://registry.npmjs.org

```
Beyond this, the instructions work!

On opening a P project with the new plugin, VS code reported the plugin crashed multiple times. Error reported:
```
Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET program, but dotnet-/Users/esthersu/P/PLanguageServer/bin/Debug/net7.0/PLanguageServer.dll does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.
[Error - 9:50:56 AM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Info  - 9:50:56 AM] Connection to server got closed. Server will restart.
true
[Error - 9:50:56 AM] p-vscode client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET program, but dotnet-/Users/esthersu/P/PLanguageServer/bin/Debug/net7.0/PLanguageServer.dll does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.
[Error - 9:50:56 AM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Info  - 9:50:56 AM] Connection to server got closed. Server will restart.
true
[Error - 9:50:56 AM] p-vscode client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET program, but dotnet-/Users/esthersu/P/PLanguageServer/bin/Debug/net7.0/PLanguageServer.dll does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.
[Error - 9:50:57 AM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Info  - 9:50:57 AM] Connection to server got closed. Server will restart.
true
[Error - 9:50:57 AM] p-vscode client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 9:50:57 AM] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 
Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET program, but dotnet-/Users/esthersu/P/PLanguageServer/bin/Debug/net7.0/PLanguageServer.dll does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.
[Error - 9:50:58 AM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Info  - 9:50:58 AM] Connection to server got closed. Server will restart.
true
[Error - 9:50:58 AM] p-vscode client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 9:50:58 AM] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 
Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET program, but dotnet-/Users/esthersu/P/PLanguageServer/bin/Debug/net7.0/PLanguageServer.dll does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.
[Error - 9:50:58 AM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 9:50:58 AM] The p-vscode server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
[Error - 9:50:58 AM] p-vscode client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 9:50:58 AM] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 
```
We need to clean this up in the main branch, and experiment with PLangServer on a different experimental branch.

The P compiler works as expected through the plugin if the .pproj file is open in the editor or all editor windows are closed. Since a P project is generally of the structure like: 
```
.
├── PForeign
│   └── ForeignCode.cs
├── PSpec
│   └── Spec.p
├── PSrc
│   └── Source.p
├── PTst
│   ├── TestDriver.p
│   └── TestScripts.p
└── ProjectName.pproj
```
right now, if Source.p is only open in the editor, the `p compile` command by F5 key through the plugin fails. Is there a way to get around this, so that we always run `p compile` from the project root with F5 key, i.e., the folder containing *.pproj file?

**Comment by aman-goel** [comment]
Also, right now, if we open or close any file in the editor, the `p compile` command is triggered. If I open two files too quickly, I get the VS code error: `The task 'MyTask: Errors (2_TwoPhaseCommit)' is already active.`.
Is it possible to resolve this?

**Comment by suesther** [comment]
I fixed all the errors you commented on. Should I push all my changes again? I changed things so that the extension doesn't attempt to connect with a server anymore. Also, the VSCode error for the task should be fixed now. And the "p compile" command should now work from any file.

**Comment by suesther** [comment]
I made a change so that the Error Reporting only occurs when the user changes a ".p" file and saves it. I also commented out the language server implementation. And, the P grammar highlighting errors should be fixed now.

**Comment by aman-goel** [comment]
> I made a change so that the Error Reporting only occurs when the user changes a ".p" file and saves it. I also commented out the language server implementation. And, the P grammar highlighting errors should be fixed now.

Thanks @suesther for the changes. It looks good now.
One small thing I see now is that compile errors are not getting displayed in the Problems tab in VS code (unlike before). Having them in the Problems tab was neat, since clicking them directly jumps to the line where the error is reported.

**Comment by suesther** [comment]
For me, the compile errors are displayed in the Problems tab in VS Code. Are you sure that your file has errors?
Screenshot 2023-06-21 at 11 37 34 AM

**Comment by aman-goel** [comment]
> 

My mistake. The Problems tab is indeed showing compile errors. However, they remain stale at times.
Say you have a single .p file open in the editor. And press F5 to compile it. Say it reports compile error ERROR1. Now even after correcting ERROR1 and pressing F5, terminal compiles P model without any error. But Problems tab is not updated. The reason is Problems tab is getting updated whenever you switch editor from one file to another. But not on F5.
Terminal and Problems tabs should be updated always together.

Do you see the same on your end?

**Comment by aman-goel** [comment]
Also, I still see the VS code warning: "The task 'MyTask: Errors (2_TwoPhaseCommit)' is already active." when switching to different .p files in the editor too quickly.
Do you see the same?

**Review by aman-goel — APPROVED** [review]

**Comment by aman-goel** [comment]
Thanks for all updates. Looking solid!

**Pull request merged**
